### PR TITLE
Added monitoring tool choose hint

### PR DESCRIPTION
**Pull request by timba**
Redux DevTools Chrome extension appears to be the easiest to integrate
Redux monitoring tool for Chrome.

### CODE REVIEW

**Comment by et1975** [comment]
Thanks, maybe add a link to install one too?

**Comment by timba** [comment]
Yep, I'll do

**Comment by MangelMaxime** [comment]
I would prefer linking this repo: https://github.com/zalmoxisus/redux-devtools-extension and generalize the message for browsers (chrome, firefox)

Yes, just because I am using Firefox :p

**Comment by timba** [comment]
@MangelMaxime I need to experiment with Firefox because I haven't tried it yet, and then I will send update.

**Pull request merged**
