### PR TITLE
Fall graciously when coders cannot be generated

### PR DESCRIPTION
**Pull request by alfonsogarciacaro**
First attempt at fixing #25, please have a look if you have a moment. I've made so you can pass anything for deflating/inflating (not only Thoth.Json) although the `ITransformer` interface may not be very intuitive. Let me try this in my project before merging.

### CODE REVIEW

**Comment by et1975** [comment]
I don't see a need for interfaces since there's no state to share between the methods or calls, but seems ok otherwise.

**Comment by alfonsogarciacaro** [comment]
It was just to group the two functions and give them a name. But actually in my tests I've notice the generated encoder can fail not at the time of creation but also later so I do need to keep some state (to prevent logging too many warnings) but I've done it just using a closure, so we can change the interface back to two functions if you prefer.

Anyways, this should be working now. So you it's ok to merge and push :)

BTW, do you know why Appveyor is failing? The log is empty.

**Comment by et1975** [comment]
Appveyor doesn't have RTM VS2019 images yet it seems. 
>we can change the interface back to two functions if you prefer.

Yes please.

**Comment by alfonsogarciacaro** [comment]
Done :)

**Comment by et1975** [comment]
Thank you! I'll release it shortly...

**Pull request merged**
